package Pojo;
// Generated Mar 23, 2015 5:14:14 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer idGroup;
     private String name;
     private String description;
     private int isActive;
     private Set staffCourseGroups = new HashSet(0);
     private Set courses = new HashSet(0);
     private Set users = new HashSet(0);

    public Group() {
    }

	
    public Group(String name, String description, int isActive) {
        this.name = name;
        this.description = description;
        this.isActive = isActive;
    }
    public Group(String name, String description, int isActive, Set staffCourseGroups, Set courses, Set users) {
       this.name = name;
       this.description = description;
       this.isActive = isActive;
       this.staffCourseGroups = staffCourseGroups;
       this.courses = courses;
       this.users = users;
    }
   
    public Integer getIdGroup() {
        return this.idGroup;
    }
    
    public void setIdGroup(Integer idGroup) {
        this.idGroup = idGroup;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }
    public Set getStaffCourseGroups() {
        return this.staffCourseGroups;
    }
    
    public void setStaffCourseGroups(Set staffCourseGroups) {
        this.staffCourseGroups = staffCourseGroups;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


