package Pojo;
// Generated Mar 23, 2015 5:14:14 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lab generated by hbm2java
 */
public class Lab  implements java.io.Serializable {


     private Integer idLab;
     private Course course;
     private String name;
     private String description;
     private Date startDate;
     private Date endDate;
     private int enableUpload;
     private Date uploadEndDate;
     private Set userAssistances = new HashSet(0);
     private Set userDeliveries = new HashSet(0);

    public Lab() {
    }

	
    public Lab(Course course, String name, String description, Date startDate, Date endDate, int enableUpload, Date uploadEndDate) {
        this.course = course;
        this.name = name;
        this.description = description;
        this.startDate = startDate;
        this.endDate = endDate;
        this.enableUpload = enableUpload;
        this.uploadEndDate = uploadEndDate;
    }
    public Lab(Course course, String name, String description, Date startDate, Date endDate, int enableUpload, Date uploadEndDate, Set userAssistances, Set userDeliveries) {
       this.course = course;
       this.name = name;
       this.description = description;
       this.startDate = startDate;
       this.endDate = endDate;
       this.enableUpload = enableUpload;
       this.uploadEndDate = uploadEndDate;
       this.userAssistances = userAssistances;
       this.userDeliveries = userDeliveries;
    }
   
    public Integer getIdLab() {
        return this.idLab;
    }
    
    public void setIdLab(Integer idLab) {
        this.idLab = idLab;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public int getEnableUpload() {
        return this.enableUpload;
    }
    
    public void setEnableUpload(int enableUpload) {
        this.enableUpload = enableUpload;
    }
    public Date getUploadEndDate() {
        return this.uploadEndDate;
    }
    
    public void setUploadEndDate(Date uploadEndDate) {
        this.uploadEndDate = uploadEndDate;
    }
    public Set getUserAssistances() {
        return this.userAssistances;
    }
    
    public void setUserAssistances(Set userAssistances) {
        this.userAssistances = userAssistances;
    }
    public Set getUserDeliveries() {
        return this.userDeliveries;
    }
    
    public void setUserDeliveries(Set userDeliveries) {
        this.userDeliveries = userDeliveries;
    }




}


