package Pojo;
// Generated Mar 23, 2015 5:14:14 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Notification generated by hbm2java
 */
public class Notification  implements java.io.Serializable {


     private Integer idNotification;
     private String message;
     private Set users = new HashSet(0);
     private Set users_1 = new HashSet(0);

    public Notification() {
    }

	
    public Notification(String message) {
        this.message = message;
    }
    public Notification(String message, Set users, Set users_1) {
       this.message = message;
       this.users = users;
       this.users_1 = users_1;
    }
   
    public Integer getIdNotification() {
        return this.idNotification;
    }
    
    public void setIdNotification(Integer idNotification) {
        this.idNotification = idNotification;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getUsers_1() {
        return this.users_1;
    }
    
    public void setUsers_1(Set users_1) {
        this.users_1 = users_1;
    }




}


