package Pojo;
// Generated Mar 23, 2015 5:14:14 PM by Hibernate Tools 3.6.0



/**
 * StaffCourseGroup generated by hbm2java
 */
public class StaffCourseGroup  implements java.io.Serializable {


     private StaffCourseGroupId id;
     private Group group;
     private User user;
     private Course course;

    public StaffCourseGroup() {
    }

    public StaffCourseGroup(StaffCourseGroupId id, Group group, User user, Course course) {
       this.id = id;
       this.group = group;
       this.user = user;
       this.course = course;
    }
   
    public StaffCourseGroupId getId() {
        return this.id;
    }
    
    public void setId(StaffCourseGroupId id) {
        this.id = id;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }




}


