package Pojo;
// Generated Mar 23, 2015 5:14:14 PM by Hibernate Tools 3.6.0



/**
 * UserAssistance generated by hbm2java
 */
public class UserAssistance  implements java.io.Serializable {


     private UserAssistanceId id;
     private User user;
     private Lab lab;
     private int serverd;
     private int countServed;
     private String comment;

    public UserAssistance() {
    }

    public UserAssistance(UserAssistanceId id, User user, Lab lab, int serverd, int countServed, String comment) {
       this.id = id;
       this.user = user;
       this.lab = lab;
       this.serverd = serverd;
       this.countServed = countServed;
       this.comment = comment;
    }
   
    public UserAssistanceId getId() {
        return this.id;
    }
    
    public void setId(UserAssistanceId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Lab getLab() {
        return this.lab;
    }
    
    public void setLab(Lab lab) {
        this.lab = lab;
    }
    public int getServerd() {
        return this.serverd;
    }
    
    public void setServerd(int serverd) {
        this.serverd = serverd;
    }
    public int getCountServed() {
        return this.countServed;
    }
    
    public void setCountServed(int countServed) {
        this.countServed = countServed;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


